### PR TITLE
install google cloud sdk on travis

### LINKED ISSUE #267: Set up gcloud on Travis
so that everything that depends on it including PathResolver works

### PR DESCRIPTION
**Pull request by elharo**
fix #267

### CODE REVIEW

**Comment by briandealwis** [comment]
How do we pass in the location so `PathResolver` and friends find it?

**Comment by elharo** [comment]
@briandealwis @meltsufin PathResolver starts by looking in the path, and here we export this dIrectory into the local PATH:

export PATH=$PWD/google-cloud-sdk/bin:$PATH

**Comment by briandealwis** [comment]
Ah right.  LGTM.

**Comment by elharo** [comment]
Hmm, another of those weird situations where the pr/ fails and push succeeds. Actually that makes sense here. The test I'm putting back in won't pass with the old setup. I'm going to merge, but holler if things start breaking.

**Pull request merged**
