### PR TITLE
com.google.gcp to com.google.cloud.tools

### LINKED ISSUE #38: Pick a package name
Before we get any further down this road, let's pick a package name we can stick to. Right now we have

com.google.gcp.eclipse

This may need to change to 

com.google.cloud.tools.eclipse

or something similar. 

The sooner we make this change (or decide to stick to what we have) the less churn in our repo.

### PR DESCRIPTION
**Pull request by elharo**
Close #38 

@akerekes @briandealwis I want to get this done while we don't have a lot of other work in flight.  I've left "gcp" in things like a few file names and repo names. Those are easier to change later if we feel like it.

### CODE REVIEW

**Comment by elharo** [comment]
Not sure why this is not offering to squash my commits.

**Comment by briandealwis** [comment]
The "Merge pull request" turns into a "Confirm squash and commit" button.

I found one missed reference to `com.google.gcp.eclipse.suite.e45.feature` in `gcp-repo/category.xml`.  I guess Travis must have cached that feature, which accounts for the unexpected reactor ordering.

Otherwise LGTM.

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] trunk
[INFO] google-cloud-plugin-eclipse.repo
[INFO] com.google.cloud.tools.eclipse.appengine.localserver
[INFO] com.google.cloud.tools.eclipse.suite.e45.feature
[INFO] com.google.cloud.tools.eclipse.appengine.localserver.test
[INFO] gcp-eclipse-mars
```

**Comment by briandealwis** [comment]
> I guess Travis must have cached that feature, which accounts for the unexpected reactor ordering.

I suspect this must have happened previously when we were using Travis' default `install` command which caused a `mvn install`. @elharo perhaps you could [clear the Travis cache](https://travis-ci.org/GoogleCloudPlatform/gcloud-eclipse-tools/caches) (I don't seem to be able to do it).

**Comment by elharo** [comment]
So when I press "Merge pull request" the button turns into "Confirm squash and Merge"?

**Comment by elharo** [comment]
Trying to clear the cache but I get "There was an error while loading data."

**Comment by briandealwis** [comment]
Yes: the button changes to a confirmation button with a drop down with the other merge options and the other option is disabled.

I had the same error trying to access the Travis cache page.  I thought it might be a permission problem on my account.

**Pull request merged**
