### PR TITLE
Add new plugins to features manifest

### LINKED ISSUE #339: setup update site
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5 0.1.0.201607111634 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607111634)
  Missing requirement: GCloud for Eclipse App Engine Local Server 0.1.0.201607111634 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201607111634) requires 'bundle com.google.cloud.tools.eclipse.sdk 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 4.5 0.1.0.201607111634 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607111634)
    To: com.google.cloud.tools.eclipse.appengine.localserver [0.1.0.201607111634]

### PR DESCRIPTION
**Pull request by elharo**
@briandealwis  fix #339

### CODE REVIEW

**Comment by elharo** [comment]
still doesn't seem to be working. I'm not sure why. Even when I split open the zip the version is there as 0.1.0 but eclipse can't find it on install.

**Comment by elharo** [comment]
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5 0.1.0.201607111634 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607111634)
  Missing requirement: GCloud for Eclipse App Engine Local Server 0.1.0.201607111634 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201607111634) requires 'bundle com.google.cloud.tools.eclipse.sdk 0.0.0' but it could not be found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 4.5 0.1.0.201607111634 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 0.1.0.201607111634)
    To: com.google.cloud.tools.eclipse.appengine.localserver [0.1.0.201607111634]

**Comment by elharo** [comment]
still don't know why this isn't working. I wonder if there's a way to test this other than manually?

**Comment by briandealwis** [comment]
Might be able to create a test using the [`tycho-eclipserun-plugin`](https://wiki.eclipse.org/Tycho/Additional_Tools#tycho-eclipserun-plugin) to invoke the _p2 director_.  The [Tycho wiki page](https://wiki.eclipse.org/Tycho/Additional_Tools#tycho-eclipserun-plugin) shows an example of doing something like this.

**Comment by elharo** [comment]
FYI, I'm going to precommit to spending no more than the rest of Tuesday trying to debug this. If at that point, we still can't get the plugin to install, I'm going to back out the dependency on the sdk package, even if it means going back to direct dependence on PathResolver. 

Then we can add some tests for this, and move forward again.

**Comment by briandealwis** [comment]
The problem is that the feature is missing `.sdk.ui` too.

**Comment by elharo** [comment]
doesn't match the error message but let me try that

On Tue, Jul 12, 2016 at 10:08 AM, Brian de Alwis <notifications@github.com>
wrote:

> The problem is that the feature is missing .sdk.ui too.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/340#issuecomment-232058620>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA9X6DfqezbI-7dKgMJbQuJvd_q8eN-Uks5qU5_sgaJpZM4JJwPt>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by elharo** [comment]
Adding.sk.ui does not appear to have fixed the problem. :-(

**Comment by briandealwis** [comment]
Strange, because that worked for me!

**Comment by elharo** [comment]
OK, stranger. It just worked for me on my Linux box. Investigating...

On Tue, Jul 12, 2016 at 10:59 AM, Brian de Alwis <notifications@github.com>
wrote:

> Strange, because that worked for me!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/pull/340#issuecomment-232075078>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AA9X6NWZ3sWrUCTMO1l0yURjaPta7fM_ks5qU6vngaJpZM4JJwPt>
> .
>



-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by elharo** [comment]
PTAL @briandealwis

**Pull request merged**
