### PR TITLE
setup list of App Engine allowed classes

### PR DESCRIPTION
**Pull request by elharo**
@akerekes @briandealwis

### CODE REVIEW

**Comment by briandealwis** [comment]
I don't think you should commit `.project` since it's just churn.  Otherwise LGTM.

**Comment by elharo** [comment]
I wish eclipse did not insist on mucking with our source tree. I'd prefer not to have any of these .project, .settings, .classpath files at all but that's not the way Eclipse works. I don't know why it decidd to move things around in this .project file. Is the ordering significant?

**Comment by elharo** [comment]
Is there some command to remove a file from a pull request? (i.e. revert it to origin/master) This is trivial in perforce, but in git it doesn't seem possible.

**Comment by elharo** [comment]
For duture reference:

15797  [2016-04-08 12:46:41 -0400] git reset --soft HEAD~1
15798  [2016-04-08 12:47:05 -0400] git reset HEAD plugins/com.google.cloud.tools.eclipse.appengine.localserver.test/.project
15799  [2016-04-08 12:47:25 -0400] git commit -m "setup list of App Engine allowed classes"
15800  [2016-04-08 12:47:40 -0400] git push -f origin util

**Pull request merged**
