### PR TITLE
project loc environment variable

### PR DESCRIPTION
**Pull request by elharo**
#157

### CODE REVIEW

**Comment by briandealwis** [comment]
This doesn't do much unfortunately.

screen shot 2016-05-18 at 3 54 28 pm

**Comment by elharo** [comment]
The question is whether it will find the right directory when attached. If so, we can futz with the error detection.

Or is there API somewhere to resolve ${PROJECT_LOC} from inside out code?

relevant info:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=229633
http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2FresInt_linked.htm

Or maybe what we need to do is allow relative paths here and resolve them ourselves  later during project creation?

**Comment by briandealwis** [comment]
I think we've misunderstood the purpose of this field: this is a directory where our server support should publish the webapps-to-be-run in a format supported by our dev server.  So for a tomcat installation, this might be `/opt/lib/tomcat/webapps/`. Since we're not expecting to have a long-lived deployments, I think these fields are internal and should not be visible to the user.

**Comment by elharo** [comment]
Yes, I need to rethink how, when, and where the exploded war gets passed to dev_appserver.py

**Comment by elharo** [comment]
No longer relevant

**Pull request closed without merging**
