### PR TITLE
Use app-tools-lib-for-java to locate SDK

### LINKED ISSUE #9: Autolocate gcloud SDK if present
Rather than making user select it.

### PR DESCRIPTION
**Pull request by elharo**
fix #9 
@briandealwis Please review especially how this is imported. Any thoughts on making this run in Eclipse and/or testing manually?

### CODE REVIEW

**Comment by elharo** [comment]
Not sure if this is related, but I'm not yet able to install this plugin:

Cannot complete the install because one or more required items could
not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5
0.1.0.201606061716
(com.google.cloud.tools.eclipse.suite.e45.feature.feature.group
0.1.0.201606061716)
  Missing requirement: GCloud for Eclipse App Engine Local Server
0.1.0.201606061716
(com.google.cloud.tools.eclipse.appengine.localserver
0.1.0.201606061716) requires 'bundle
com.google.cloud.tools.eclipse.appengine.ui 0.1.0' but it could not be
found
  Cannot satisfy dependency:
    From: Google Cloud Platform for Eclipse 4.5 0.1.0.201606061716
(com.google.cloud.tools.eclipse.suite.e45.feature.feature.group
0.1.0.201606061716)
    To: com.google.cloud.tools.eclipse.appengine.localserver
[0.1.0.201606061716]

I need to try doing this from head.

**Comment by briandealwis** [comment]
Using PathResolver directly doesn't feel very Eclipse-y.  The developer should be able to configure the location, and our code should be independent of that.

I'm about 70% of the way to creating a plugin that configures the `CloudSdk` instance from a preference, and allows the user to change the location via a preference page.  I make the CloudSdk instance available as an OSGi service, which means it can be pulled in via dependency injection or other service discovery mechanisms (`IServiceLocator`).  I'll get it finished today.

**Comment by elharo** [comment]
This just sets up the initial default choice. The user can still change it in the runtime config (though it occurs to me I should test what happens when gcloud isn't found.)

**Comment by elharo** [comment]
PTAL @briandealwis this seems to work now.

**Comment by elharo** [comment]
I may have spoken too soon. Now compiles at the command line, but Eclipse still can't find PathResolver. Any suggestions?

**Comment by elharo** [comment]
image

**Comment by elharo** [comment]
java.lang.NoClassDefFoundError: com/google/cloud/tools/appengine/cloudsdk/PathResolver
	at com.google.cloud.tools.eclipse.appengine.newproject.CreateAppEngineStandardWtpProject.findCloudSdk(CreateAppEngineStandardWtpProject.java:156)

**Comment by elharo** [comment]
No available bundle exports package 'com.google.cloud.tools.appengine.cloudsdk'

**Comment by elharo** [comment]
maybe I need to rebuild the target platform? checking...

**Comment by elharo** [comment]
Bingo! That did it. Still need to check whether the change I made in app-tools-lib-for-java is actually needed but meanwhile PTAL

**Comment by briandealwis** [comment]
LGTM; I'll fix this up differently with the preference work I mentioned above, but that's just a matter of changing the `findCloudSdk` method.

**Pull request merged**
