### PR TITLE
set title and description in wizard

### PR DESCRIPTION
**Pull request by elharo**
Get rid of the big blank space in the wizard.
titleanddescription

### CODE REVIEW

**Comment by elharo** [comment]
@nbashirbello @briandealwis #155

**Comment by briandealwis** [comment]
LGTM

**Comment by elharo** [comment]
See if instead of hard coding strings we can read the  wizard.name and wizard.description properties from plugins/com.google.cloud.tools.eclipse.appengine.newproject/plugin.properties

**Comment by elharo** [comment]
close #155

**Pull request merged**
